const numero1 = 10;
const numero3 = 30;

console.log(numero1);

// Muestra un error en caso de existir y continúa con el código
try {
    console.log(numero2)
} catch (error) {
    console.log(error)
}

console.log(numero3)